spring:
  datasource:
    url: jdbc:mysql://47.107.72.240:3306/siseoj_test?serverTimezone=UTC
    username: root
    password: 1234,abcd
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml